/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.s11059003_hw11;

import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.parser.ParseException;
import java.awt.*;

/**
 *
 * @author USER
 */
public class gui extends javax.swing.JFrame {
    private S11059003_HW11 test;
    public Graphics g1;
    public Graphics2D g2;
    private boolean is_first = false;
    public int width;
    public int height;
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        month.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date5 = new java.awt.Label();
        date12 = new java.awt.Label();
        date16 = new java.awt.Label();
        label3 = new java.awt.Label();
        month = new javax.swing.JSpinner();
        label4 = new java.awt.Label();
        in = new java.awt.TextField();
        download = new java.awt.Button();
        out = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        date1 = new java.awt.Label();
        date2 = new java.awt.Label();
        date3 = new java.awt.Label();
        date4 = new java.awt.Label();
        date_5 = new java.awt.Label();
        date6 = new java.awt.Label();
        label2 = new java.awt.Label();
        state = new java.awt.Label();

        date5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date5.setText("Date1");

        date12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date12.setText("Date1");

        date16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date16.setText("Date1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Year: 2024, Month:");

        month.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                monthStateChanged(evt);
            }
        });

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Stock code:");

        download.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        download.setLabel("Download");
        download.setName(""); // NOI18N
        download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadActionPerformed(evt);
            }
        });

        out.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout outLayout = new javax.swing.GroupLayout(out);
        out.setLayout(outLayout);
        outLayout.setHorizontalGroup(
            outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outLayout.setVerticalGroup(
            outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Draw 5MA & 10MA");

        date1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date1.setText("Date1");

        date2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date2.setText("Date2");

        date3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date3.setText("Date3");

        date4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date4.setText("Date4");

        date_5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date_5.setText("Date5");

        date6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        date6.setText("Date6");

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Day");

        state.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(download, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(date_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(download, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_monthStateChanged
        // TODO add your handling code here:
        if(!month.getValue().toString().isEmpty() && month.getValue().toString() != null) {
            int value = (int) month.getValue();
            if (value < 1) {
                month.setValue(12);
            } else if (value > 12) {
                month.setValue(1);
            }
        }
    }//GEN-LAST:event_monthStateChanged

    private void downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(in.getText().length() > 0) {
                String m = month.getValue().toString();
                if (m.matches("[1-9]")) {
                    m = "0" + m;
                }
                test = new S11059003_HW11(this, m, in.getText());
                test.start();
            }
            else {
                state.setText("ERROR");
                repaint(out.getGraphics(), g2, width, height);
            }
        } 
        catch (ParseException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_downloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    System.setOut(new PrintStream(System.out, true, "UTF-8"));
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                }
                new gui().setVisible(true);
            }
        });
    }
    
    protected void paint(Graphics g, Stock[] stocks) {
        width = out.getWidth();
        height = out.getHeight();
        int pad = 10;

        if (stocks == null || stocks.length == 0){
            return;
        }

        double com5 = Double.MIN_VALUE;
        double com10 = Double.MIN_VALUE;
        int maxDay = Integer.MIN_VALUE;

        for (Stock s : stocks) {
            if (s.price != -1) {
                com5 = Math.max(com5, s.avg5);
                com10 = Math.max(com10, s.avg10);
            }
            maxDay = Math.max(maxDay, s.day);
        }

        //System.out.println("Before: " + com5 + "   " + com10 + "    " + maxDay);
        //System.out.println("Size: " + width + "   " + height);
        double x = maxDay * 1.0 / width;
        double y5 = com5 / height;
        double y10 = com10 / height;
        //System.out.println("After: " + x + "   " + y5 + "    " + y10);

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        // clean JPanel
        g1 = g;
        g2 = g2d;
        repaint(g, g2d, width, height);

        //System.out.println("5MA");
        g2d.setColor(Color.RED);
        for (int i = 0; i < stocks.length - 1; i++) {
            if (stocks[i].avg5 != -1 && stocks[i+1].avg5 != -1) {
                int x1 = (int) (int) (stocks[i].day / x);
                int y1 = (int) (stocks[i].avg5 / y5);
                int x2 = (int) (stocks[i+1].day / x);
                int y2 = (int) (stocks[i+1].avg5 / y5);
                //System.out.println("i=" + i + " (" + x1 + "," + y1 + ") (" + x2 + "," + y2 + ")");
                g2d.drawLine(x1, y1, x2, y2);
            }
        }

        //System.out.println("10MA");
        g2d.setColor(Color.BLUE);
        for (int i = 0; i < stocks.length - 1; i++) {
            if (stocks[i].avg10 != -1 && stocks[i+1].avg10 != -1) {
                int x1 = (int) (int) (stocks[i].day / x);
                int y1 = (int) (stocks[i].avg10 / y5);
                int x2 = (int) (stocks[i+1].day / x);
                int y2 = (int) (stocks[i+1].avg10 / y5);
                //System.out.println("i=" + i + " (" + x1 + "," + y1 + ") (" + x2 + "," + y2 + ")");
                g2d.drawLine(x1, y1, x2, y2);
            }
        }
    }
    
    public void repaint(Graphics g, Graphics2D g2d, int w, int h) {
        if(g != null && g2d != null) {
            g.clearRect(0, 0, w, h);

            // Redraw border
            g2d.setColor(Color.BLACK);
            g2d.drawLine(0, 0, w-1, 0);
            g2d.drawLine(0, 0, 0, h-1);
            g2d.drawLine(w-1, 0, w-1, h-1);
            g2d.drawLine(0, h-1, w-1, h-1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Label date1;
    private java.awt.Label date12;
    private java.awt.Label date16;
    public java.awt.Label date2;
    public java.awt.Label date3;
    public java.awt.Label date4;
    private java.awt.Label date5;
    public java.awt.Label date6;
    public java.awt.Label date_5;
    private java.awt.Button download;
    public java.awt.TextField in;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JSpinner month;
    public javax.swing.JPanel out;
    public java.awt.Label state;
    // End of variables declaration//GEN-END:variables
}
